version: '3'
services:
  backend2-dev-db:
    image: mysql:8.0
    hostname: localhost
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zizle
      MYSQL_PASSWORD: password
    networks:
      - coderzhunt
networks:
  coderzhunt:
