export const SWAGGER_API_TAG = {
  AUTH: 'AUTH',
  CUSTOMER: 'CUSTOMER',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  NOTES: 'NOTES',
  FAKE: 'FAKE',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  CHAT: 'CHAT',
  COINS: 'COINS',
  MODERATOR: 'MODERATOR',
  PAYMENTS: 'PAYMENTS',
  GALLERY: 'GALLERY',
};
